version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    container_name: visits-backend
    ports:
      - "8000:8000"
    volumes:
      - ../data:/app/data:ro
    environment:
      - PYTHONPATH=/app
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    container_name: visits-frontend
    ports:
      - "8501:8501"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - PYTHONPATH=/app
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
